//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oocw.Base.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Oocw.Base.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 able
        ///about
        ///above
        ///abroad
        ///according
        ///accordingly
        ///across
        ///actually
        ///adj
        ///after
        ///afterwards
        ///again
        ///against
        ///ago
        ///ahead
        ///ain&apos;t
        ///all
        ///allow
        ///allows
        ///almost
        ///alone
        ///along
        ///alongside
        ///already
        ///also
        ///although
        ///always
        ///am
        ///amid
        ///amidst
        ///among
        ///amongst
        ///an
        ///and
        ///another
        ///any
        ///anybody
        ///anyhow
        ///anyone
        ///anything
        ///anyway
        ///anyways
        ///anywhere
        ///apart
        ///appear
        ///appreciate
        ///appropriate
        ///are
        ///aren&apos;t
        ///around
        ///as
        ///a&apos;s
        ///aside
        ///ask
        ///asking
        ///associated
        ///at
        ///available
        ///away
        ///awfully
        ///back
        ///backward
        ///backwards
        ///be
        ///became
        ///because [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string stopwords_en {
            get {
                return ResourceManager.GetString("stopwords_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 あそこ
        ///あっ
        ///あの
        ///あのかた
        ///あの人
        ///あり
        ///あります
        ///ある
        ///あれ
        ///い
        ///いう
        ///います
        ///いる
        ///う
        ///うち
        ///え
        ///お
        ///および
        ///おり
        ///おります
        ///か
        ///かつて
        ///から
        ///が
        ///き
        ///ここ
        ///こちら
        ///こと
        ///この
        ///これ
        ///これら
        ///さ
        ///さらに
        ///し
        ///しかし
        ///する
        ///ず
        ///せ
        ///せる
        ///そこ
        ///そして
        ///その
        ///その他
        ///その後
        ///それ
        ///それぞれ
        ///それで
        ///た
        ///ただし
        ///たち
        ///ため
        ///たり
        ///だ
        ///だっ
        ///だれ
        ///つ
        ///て
        ///で
        ///でき
        ///できる
        ///です
        ///では
        ///でも
        ///と
        ///という
        ///といった
        ///とき
        ///ところ
        ///として
        ///とともに
        ///とも
        ///と共に
        ///どこ
        ///どの
        ///な
        ///ない
        ///なお
        ///なかっ
        ///ながら
        ///なく
        ///なっ
        ///など
        ///なに
        ///なら
        ///なり
        ///なる
        ///なん
        ///に
        ///において
        ///における
        ///について
        ///にて
        ///によって
        ///により
        ///による
        ///に対して
        ///に対する
        ///に関する
        ///の
        ///ので
        ///のみ
        ///は
        ///ば
        ///へ
        ///ほか
        ///ほとんど
        ///ほど
        ///ます
        ///また
        ///または
        ///まで
        ///も
        ///もの
        ///ものの
        ///や
        ///よう
        ///より
        ///ら
        ///られ
        ///られる
        ///れ
        ///れ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string stopwords_ja {
            get {
                return ResourceManager.GetString("stopwords_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 zh
        ///en
        ///ja
        ///ObjectId
        ///ocwId
        ///None
        ///True
        ///False 的本地化字符串。
        /// </summary>
        internal static string stopwords_py {
            get {
                return ResourceManager.GetString("stopwords_py", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 、
        ///。
        ///〈
        ///〉
        ///《
        ///》
        ///一个
        ///一些
        ///一何
        ///一切
        ///一则
        ///一方面
        ///一旦
        ///一来
        ///一样
        ///一种
        ///一般
        ///一转眼
        ///万一
        ///上
        ///上下
        ///下
        ///不
        ///不仅
        ///不但
        ///不光
        ///不单
        ///不只
        ///不外乎
        ///不如
        ///不妨
        ///不尽
        ///不尽然
        ///不得
        ///不怕
        ///不惟
        ///不成
        ///不拘
        ///不料
        ///不是
        ///不比
        ///不然
        ///不特
        ///不独
        ///不管
        ///不至于
        ///不若
        ///不论
        ///不过
        ///不问
        ///与
        ///与其
        ///与其说
        ///与否
        ///与此同时
        ///且
        ///且不说
        ///且说
        ///两者
        ///个
        ///个别
        ///中
        ///临
        ///为
        ///为了
        ///为什么
        ///为何
        ///为止
        ///为此
        ///为着
        ///乃
        ///乃至
        ///乃至于
        ///么
        ///之
        ///之一
        ///之所以
        ///之类
        ///乌乎
        ///乎
        ///乘
        ///也
        ///也好
        ///也罢
        ///了
        ///二来
        ///于
        ///于是
        ///于是乎
        ///云云
        ///云尔
        ///些
        ///亦
        ///人
        ///人们
        ///人家
        ///什
        ///什么
        ///什么样
        ///今
        ///介于
        ///仍
        ///仍旧
        ///从
        ///从此
        ///从而
        ///他
        ///他人
        ///他们
        ///他们们
        ///以
        ///以上
        ///以为
        ///以便
        ///以免
        ///以及
        ///以故
        ///以期
        ///以来
        ///以至
        ///以至于
        ///以致
        ///们
        ///任
        ///任何
        ///任凭
        ///会
        ///似的
        ///但
        ///但凡
        ///但是
        ///何
        ///何以
        ///何 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string stopwords_zh {
            get {
                return ResourceManager.GetString("stopwords_zh", resourceCulture);
            }
        }
    }
}
